version: "3.7"
services:
  phpmyadmin_app:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=192.168.12.12
      - PMA_PORT=3306
      - PMA_VERBOSE=mysqlserver
      - PMA_USER=root
      - PMA_PASSWORD=mypassword
    container_name: phpmyadmin_app
    hostname: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      mysqlserver_redisserver_network:
        ipv4_address: 192.168.12.11

  mysqlserver_app:
    image: mysql:5.7.24
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword 
    container_name: mysqlserver_app
    hostname: mysqlserver
    restart: always
    ports:
      - "3306:3306"
    networks:
      mysqlserver_redisserver_network:
        ipv4_address: 192.168.12.12
    volumes:
      - /data1/export/app/mysqlserver:/var/lib/mysql

  phpredisadmin_app:
    image: erikdubbelboer/phpredisadmin:latest
    environment:
      - REDIS_1_HOST=192.168.12.14
      - REDIS_1_NAME=redisserver
    container_name: phpredisadmin_app
    hostname: phpredisadmin
    restart: always
    ports:
      - "8081:80"
    networks:
      mysqlserver_redisserver_network:
        ipv4_address: 192.168.12.13

  redisserver_app:
    image: redis:5.0
    container_name: redisserver_app
    hostname: redisserver
    restart: always
    ports:
      - "6379:6379"
    networks:
      mysqlserver_redisserver_network:
        ipv4_address: 192.168.12.14
    volumes:
      - /data1/export/app/redisserver:/data

networks:
  mysqlserver_redisserver_network:
    name: mysqlserver_redisserver_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
